<%@ LANGUAGE="VBScript" %>
<html>
<head>


<%
bannerType = "rugby"
%>

<p><!--#include virtual='../htdocs/includes/standardpage.inc'--></p>
<DIV CLASS="textbox">
<P><A CLASS="Off-static-link" HREF="http://www.grfc.co.uk/booksys/taskcal.asp">Back to Club Task system</A></P>

<%

Dim Error_Message
Error_Message = ""

Dim Previous_Status
Previous_Status = ""


If IsDate(Request.Form("txtDate")) = false then
	Error_Message = Error_Message & "Input Error - Please enter a valid date in the format dd/mm/yyyy." & "<br><br>"
Else
   'Ok passed validtion
   If left(Request.Form("txtDate"),5) = "29/02" or left(Request.Form("txtDate"),5) = "29.02" then
	  	Error_Message = Error_Message & "Input Error - The Date 29th Feb can not be used." & "<br><br>"
   End If
End If

If Request.Form("txtTitle") = "" then
   Error_Message = Error_Message & "Input Error - The Title for the task must be entered." & "<br><br>"

	If len(trim(Request.Form("txtTitle"))) > 99 then
	   Error_Message = Error_Message & "Input Error - The lenght of the Title can not exceed 99 characters." & "<br><br>"
	End If
End If

If Request.Form("txtDescription") = "" then
	Error_Message = Error_Message & "Input Error - The Description of the task must be entered." & "<br><br>"
End If

If Request.Form("txtStatus") = "" then
	Error_Message = Error_Message & "Input Error - The status of the task must be entered." & "<br><br>"
End If


Dim rs


TD_Start = "<tr><td valign=top><b>"
TD_End = "</b></td><td> : </td><td valign=top>"
TD_End2 = "</td><tr>"

If Error_Message <> "" Then
   Error

%>

	<P><A CLASS="heading">Error</A></P>
	<DIV CLASS="textbox"><br><br>

<%
	Response.Write("<table border=0>")
	Response.Write("</table>")
	Response.Write("<font size=2 color=red>" & "Unable to make booking due to error : " & "<br>" &  Error_Message  & "Please press the page back button on your Internetbrowser, amend the details and save the task again." & "</font><br><br><br><br><br><br>")
	Response.Write("</DIV>")


Else
	'Ok - passed validation.

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'Update the task
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
   dim SearchStringResult
	Set rs = Server.CreateObject("ADODB.RecordSet")
	adoDatabase = "TaskCal.mdb"

	If Request.Form("Mode") = "New Entry" then
	   sqlStr = "Select * from Tasks"
	else
	   sqlStr = "Select * from Tasks where TaskNo = " & trim(Request.Form("UPDATETASKNO"))
	End If
	conStr = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" & Server.MapPath(adoDatabase) & ";Persist Security Info=False"
	rs.CursorType = 2
	rs.LockType = 3
	rs.Open sqlStr, conStr

	If Request.Form("Mode") = "New Entry" then
	   rs.Addnew
	Else
		'Modification.
	End If

	If Isnull(rs("TaskStatus")) = true then
		Previous_Status = "Open"
	Else
		Previous_Status =  rs("TaskStatus")
	End if

	rs("TaskDate") = Request.Form("txtDate")
	rs("TaskTitle")= Request.Form("txtTitle")
	rs("TaskDescription") = Request.Form("txtDescription")
	rs("LastUpdated") = Now()
	rs("TaskAssigned")= Request.Form("txtAssigned")
	If Trim(Request.Form("txtNotes")) = "" then
		rs("TaskProgress") = Request.Form("txtNotes")

	Else
		rs("TaskProgress") = rs("TaskProgress") &  Now() & " " & Request.Form("txtNotes") & "<br>"
	End If

	rs("TaskStatus") = Request.Form("txtStatus")
	'Update new or modified task
	rs.Update


	If Request.Form("Mode") = "New Entry" then
		'All work done
	else
		If (Previous_Status <> "Complete" and Previous_Status <> "Cancelled") and Request.Form("txtStatus") = "Complete" then
				 rs("TaskStatus") = Request.Form("txtStatus")
				 rs("TaskProgress") = rs("TaskProgress") &  Now() & " " & "Task Closed, New Task Auto Generated for 1 years time." & "<br>"
			rs.Update


			'Re gemerate task for a years time.
			rs.Addnew
			rs("TaskDate") = dateadd("d",365,Request.Form("txtDate"))
			rs("TaskTitle")= Request.Form("txtTitle")
			rs("TaskDescription") = Request.Form("txtDescription")
			rs("LastUpdated") = Now()
			rs("TaskAssigned")= Request.Form("txtAssigned")
			rs("TaskProgress") =  Now() & " " & "Task Auto Generated by closure of previous task." & "<br>"
			rs("TaskStatus") = "Open"
			rs.Update
		End If
	End If


	rs.Close
	Set rs = Nothing
	Set conStr = Nothing


%>
	<P><A CLASS="heading">Task Successfully Entered \ Modified</A></P><DIV CLASS="textbox">
<%
End If
%>

<p><!--#include virtual='../htdocs/includes/taskcalftr.inc'--></p>

</DIV>
</body>
</html>
</script>