<!--#include file="adovbs.inc"-->
<META http-equiv="Content-Type" content="text/html;charset=utf-8">
<META NAME="keywords" CONTENT="rugby, guildford, guildfordians RFC, surrey, kids, children, mini, junior, youth">
<META NAME="description" CONTENT="Guildfordians RFC">
<META NAME="author" CONTENT="Austin Wilkinson">
<META NAME="copyright" CONTENT="2011, Guildfordians RFC">
<base target="_top" />
<TITLE>Guildfordians RFC</TITLE>

<LINK REL="SHORTCUT ICON" HREF="http://www.grfc.co.uk/favicon.ico">
<LINK REL="STYLESHEET" HREF="/includes/grfc_2012.css?q=1" TYPE="text/css">

<!--#include virtual="/includes/alert.inc"-->

<script type="text/javascript" language="JavaScript" src="/includes/grfc.js"></script>
</HEAD>

<BODY MARGINWIDTH=0 MARGINHEIGHT=0 LEFTMARGIN=0 TOPMARGIN=0 BGCOLOR="#eeeeee">

<A NAME="top"></A>


<TABLE WIDTH="100%" CELLPADDING="0" CELLSPACING="0">

<TR HEIGHT="10">

<TD CLASS="bannerL" WIDTH="30" HEIGHT="120" ALIGN="Left" ROWSPAN="3"></TD>
<TD CLASS="bannerL" WIDTH="179" ROWSPAN="3"><A HREF="/"><IMG SRC="/nav_images/2010_crest.gif" WIDTH="179" HEIGHT="90" ALT="" ALIGN="right" BORDER="0"></A></TD>
<TD CLASS="bannerL" WIDTH="30" ROWSPAN="3"></TD>

<TD CLASS="bannerL" HEIGHT="10"></TD>

<TD CLASS="bannerR" WIDTH="10" ROWSPAN="3"></TD>

<TD CLASS="bannerR" ALIGN="Right" NOWRAP ROWSPAN="3">
&nbsp;
</TD>

</TR>

<TR HEIGHT="100">

<%
if alert then
	response.write("<TD CLASS='bannerAlert' HEIGHT='100'>" & alertMessage & "</TD>")
else
	response.write("<TD CLASS='bannerR' HEIGHT='100' NOWRAP><A HREF='/'><IMG SRC='/nav_images/2010_banner.jpg' WIDTH='600' HEIGHT='49' ALT='' ALIGN='Center' BORDER='0'></A></TD>")
end if

%>

</TR>

<TR HEIGHT="10">

<TD CLASS="bannerL" HEIGHT="10"></TD>

</TR>

</TABLE>

	<ul class="nav-menu">
		<li>
			<a href="/">Home</a>
		</li>
		<li>
			<a href="/contacts.cshtml">Contacts</a>
		</li>
		<li>
			<a href="/about.asp">About us</a>
		</li>
		<li>
			<a href="/location.asp">Location</a>
		</li>
		<li>
			<a href="/gallery.asp">Gallery</a>
		</li>
		<li>
			<a href="/festivals.asp">Festivals</a>
		</li>
		<li>
			<a href="/shop.asp">Shop</a>
		</li>
		<li>
			<a href="/bcd.asp">BCD</a>
		</li>
	</ul>
	<div class="links-menu">
		<ul>
			<li>
				<a href="/minis.aspx">Minis</a>
			</li>
			<li>
				<a href="/youth.aspx">Youth</a>
			</li>
			<li>
				<a href="/girls.aspx">Girls</a>
			</li>
			<li>
				<a href="/seniors.htm">Seniors</a>
			</li>
      <li>
        <a href="/Social.aspx">Social</a>
      </li>
      <li>
				<a href="">Members</a>
				<ul>
					<li>
						<a href="/diary.aspx">Club diary</a>
					</li>
					<li>
						<a href="/constitution.asp">Constitution</a>
					</li>
					<li>
						<a href="/cpp.asp">Child protection</a>
					</li>
					<li>
						<a href="/structure.asp">Committee structure</a>
					</li>
					<li>
						<a href="/links.asp">Links</a>
					</li>
					<li>
						<a href="/Documents.aspx">Documents</a>
					</li>
					<li>
						<a href="/Newsletters.aspx">Newsletters</a>
					</li>
					<li>
						<a href="/MatchReports.aspx">Match reports</a>
					</li>
				</ul>
			</li>
			<li>
				<a href="officials.asp">Officials</a>
				<ul>
					<li>
						<a href="/coaches.asp">Coaching resources</a>
					</li>
					<li>
						<a href="/committee.asp">Committee</a>
					</li>
					<li>
						<a href="/bcdadmin.asp">BCD admin</a>
					</li>
					<li>
						<a href="/booksys/taskcal.asp">Task calendar</a>
					</li>
					<li>
						<a href="/booksys/booking.asp">Booking system</a>
					</li>
					<li>
						<a href="/filestore.asp">File store</a>
					</li>
				</ul>
			</li>
		</ul>
	</div>

